//! ISO 3166-1 country tables, GENERATED from the `iso-codes` package's
//! `iso_3166-1.json` (public domain) on 2026-08-30 — not typed by hand and
//! not recalled from memory. Regenerate rather than edit: a hand-patched
//! entry is how issue 319 happened.
//!
//! Issue 319: the corpus stores alpha-2 in `organizations.country`, but TED
//! and its national feeds publish alpha-3 and, occasionally, a country NAME.
//! The previous fold covered ~50 alpha-3 codes chosen by hand — the EU-27
//! plus "common third countries" — so the other 151 passed through unchanged
//! and split their countries in two (`GL` beside `GRL`, 12 rows).
//!
//! **Never fold by truncating an alpha-3 to its first two letters.** SEN is
//! Senegal and SE is Sweden; BEN is Benin and BE is Belgium. The prefix looks
//! like a mapping and is not one.

/// ISO 3166-1 alpha-3 → alpha-2, all 249 assignments.
pub const ALPHA3_TO_ALPHA2: &[(&str, &str)] = &[
    ("ABW", "AW"), ("AFG", "AF"), ("AGO", "AO"), ("AIA", "AI"),
    ("ALA", "AX"), ("ALB", "AL"), ("AND", "AD"), ("ARE", "AE"),
    ("ARG", "AR"), ("ARM", "AM"), ("ASM", "AS"), ("ATA", "AQ"),
    ("ATF", "TF"), ("ATG", "AG"), ("AUS", "AU"), ("AUT", "AT"),
    ("AZE", "AZ"), ("BDI", "BI"), ("BEL", "BE"), ("BEN", "BJ"),
    ("BES", "BQ"), ("BFA", "BF"), ("BGD", "BD"), ("BGR", "BG"),
    ("BHR", "BH"), ("BHS", "BS"), ("BIH", "BA"), ("BLM", "BL"),
    ("BLR", "BY"), ("BLZ", "BZ"), ("BMU", "BM"), ("BOL", "BO"),
    ("BRA", "BR"), ("BRB", "BB"), ("BRN", "BN"), ("BTN", "BT"),
    ("BVT", "BV"), ("BWA", "BW"), ("CAF", "CF"), ("CAN", "CA"),
    ("CCK", "CC"), ("CHE", "CH"), ("CHL", "CL"), ("CHN", "CN"),
    ("CIV", "CI"), ("CMR", "CM"), ("COD", "CD"), ("COG", "CG"),
    ("COK", "CK"), ("COL", "CO"), ("COM", "KM"), ("CPV", "CV"),
    ("CRI", "CR"), ("CUB", "CU"), ("CUW", "CW"), ("CXR", "CX"),
    ("CYM", "KY"), ("CYP", "CY"), ("CZE", "CZ"), ("DEU", "DE"),
    ("DJI", "DJ"), ("DMA", "DM"), ("DNK", "DK"), ("DOM", "DO"),
    ("DZA", "DZ"), ("ECU", "EC"), ("EGY", "EG"), ("ERI", "ER"),
    ("ESH", "EH"), ("ESP", "ES"), ("EST", "EE"), ("ETH", "ET"),
    ("FIN", "FI"), ("FJI", "FJ"), ("FLK", "FK"), ("FRA", "FR"),
    ("FRO", "FO"), ("FSM", "FM"), ("GAB", "GA"), ("GBR", "GB"),
    ("GEO", "GE"), ("GGY", "GG"), ("GHA", "GH"), ("GIB", "GI"),
    ("GIN", "GN"), ("GLP", "GP"), ("GMB", "GM"), ("GNB", "GW"),
    ("GNQ", "GQ"), ("GRC", "GR"), ("GRD", "GD"), ("GRL", "GL"),
    ("GTM", "GT"), ("GUF", "GF"), ("GUM", "GU"), ("GUY", "GY"),
    ("HKG", "HK"), ("HMD", "HM"), ("HND", "HN"), ("HRV", "HR"),
    ("HTI", "HT"), ("HUN", "HU"), ("IDN", "ID"), ("IMN", "IM"),
    ("IND", "IN"), ("IOT", "IO"), ("IRL", "IE"), ("IRN", "IR"),
    ("IRQ", "IQ"), ("ISL", "IS"), ("ISR", "IL"), ("ITA", "IT"),
    ("JAM", "JM"), ("JEY", "JE"), ("JOR", "JO"), ("JPN", "JP"),
    ("KAZ", "KZ"), ("KEN", "KE"), ("KGZ", "KG"), ("KHM", "KH"),
    ("KIR", "KI"), ("KNA", "KN"), ("KOR", "KR"), ("KWT", "KW"),
    ("LAO", "LA"), ("LBN", "LB"), ("LBR", "LR"), ("LBY", "LY"),
    ("LCA", "LC"), ("LIE", "LI"), ("LKA", "LK"), ("LSO", "LS"),
    ("LTU", "LT"), ("LUX", "LU"), ("LVA", "LV"), ("MAC", "MO"),
    ("MAF", "MF"), ("MAR", "MA"), ("MCO", "MC"), ("MDA", "MD"),
    ("MDG", "MG"), ("MDV", "MV"), ("MEX", "MX"), ("MHL", "MH"),
    ("MKD", "MK"), ("MLI", "ML"), ("MLT", "MT"), ("MMR", "MM"),
    ("MNE", "ME"), ("MNG", "MN"), ("MNP", "MP"), ("MOZ", "MZ"),
    ("MRT", "MR"), ("MSR", "MS"), ("MTQ", "MQ"), ("MUS", "MU"),
    ("MWI", "MW"), ("MYS", "MY"), ("MYT", "YT"), ("NAM", "NA"),
    ("NCL", "NC"), ("NER", "NE"), ("NFK", "NF"), ("NGA", "NG"),
    ("NIC", "NI"), ("NIU", "NU"), ("NLD", "NL"), ("NOR", "NO"),
    ("NPL", "NP"), ("NRU", "NR"), ("NZL", "NZ"), ("OMN", "OM"),
    ("PAK", "PK"), ("PAN", "PA"), ("PCN", "PN"), ("PER", "PE"),
    ("PHL", "PH"), ("PLW", "PW"), ("PNG", "PG"), ("POL", "PL"),
    ("PRI", "PR"), ("PRK", "KP"), ("PRT", "PT"), ("PRY", "PY"),
    ("PSE", "PS"), ("PYF", "PF"), ("QAT", "QA"), ("REU", "RE"),
    ("ROU", "RO"), ("RUS", "RU"), ("RWA", "RW"), ("SAU", "SA"),
    ("SDN", "SD"), ("SEN", "SN"), ("SGP", "SG"), ("SGS", "GS"),
    ("SHN", "SH"), ("SJM", "SJ"), ("SLB", "SB"), ("SLE", "SL"),
    ("SLV", "SV"), ("SMR", "SM"), ("SOM", "SO"), ("SPM", "PM"),
    ("SRB", "RS"), ("SSD", "SS"), ("STP", "ST"), ("SUR", "SR"),
    ("SVK", "SK"), ("SVN", "SI"), ("SWE", "SE"), ("SWZ", "SZ"),
    ("SXM", "SX"), ("SYC", "SC"), ("SYR", "SY"), ("TCA", "TC"),
    ("TCD", "TD"), ("TGO", "TG"), ("THA", "TH"), ("TJK", "TJ"),
    ("TKL", "TK"), ("TKM", "TM"), ("TLS", "TL"), ("TON", "TO"),
    ("TTO", "TT"), ("TUN", "TN"), ("TUR", "TR"), ("TUV", "TV"),
    ("TWN", "TW"), ("TZA", "TZ"), ("UGA", "UG"), ("UKR", "UA"),
    ("UMI", "UM"), ("URY", "UY"), ("USA", "US"), ("UZB", "UZ"),
    ("VAT", "VA"), ("VCT", "VC"), ("VEN", "VE"), ("VGB", "VG"),
    ("VIR", "VI"), ("VNM", "VN"), ("VUT", "VU"), ("WLF", "WF"),
    ("WSM", "WS"), ("YEM", "YE"), ("ZAF", "ZA"), ("ZMB", "ZM"),
    ("ZWE", "ZW"),
];

/// ISO 3166-1 country NAMES (short, official and common forms, uppercased)
/// → alpha-2. The corpus holds one row spelled `LUXEMBOURG`; the table is
/// generated whole rather than special-cased, because the next feed to
/// publish a name will not pick that one.
pub const NAME_TO_ALPHA2: &[(&str, &str)] = &[
    ("AFGHANISTAN", "AF"), ("ALBANIA", "AL"),
    ("ALGERIA", "DZ"), ("AMERICAN SAMOA", "AS"),
    ("ANDORRA", "AD"), ("ANGOLA", "AO"),
    ("ANGUILLA", "AI"), ("ANTARCTICA", "AQ"),
    ("ANTIGUA AND BARBUDA", "AG"), ("ARAB REPUBLIC OF EGYPT", "EG"),
    ("ARGENTINA", "AR"), ("ARGENTINE REPUBLIC", "AR"),
    ("ARMENIA", "AM"), ("ARUBA", "AW"),
    ("AUSTRALIA", "AU"), ("AUSTRIA", "AT"),
    ("AZERBAIJAN", "AZ"), ("BAHAMAS", "BS"),
    ("BAHRAIN", "BH"), ("BANGLADESH", "BD"),
    ("BARBADOS", "BB"), ("BELARUS", "BY"),
    ("BELGIUM", "BE"), ("BELIZE", "BZ"),
    ("BENIN", "BJ"), ("BERMUDA", "BM"),
    ("BHUTAN", "BT"), ("BOLIVARIAN REPUBLIC OF VENEZUELA", "VE"),
    ("BOLIVIA", "BO"), ("BOLIVIA, PLURINATIONAL STATE OF", "BO"),
    ("BONAIRE, SINT EUSTATIUS AND SABA", "BQ"), ("BOSNIA AND HERZEGOVINA", "BA"),
    ("BOTSWANA", "BW"), ("BOUVET ISLAND", "BV"),
    ("BRAZIL", "BR"), ("BRITISH INDIAN OCEAN TERRITORY", "IO"),
    ("BRITISH VIRGIN ISLANDS", "VG"), ("BRUNEI DARUSSALAM", "BN"),
    ("BULGARIA", "BG"), ("BURKINA FASO", "BF"),
    ("BURUNDI", "BI"), ("CABO VERDE", "CV"),
    ("CAMBODIA", "KH"), ("CAMEROON", "CM"),
    ("CANADA", "CA"), ("CAYMAN ISLANDS", "KY"),
    ("CENTRAL AFRICAN REPUBLIC", "CF"), ("CHAD", "TD"),
    ("CHILE", "CL"), ("CHINA", "CN"),
    ("CHRISTMAS ISLAND", "CX"), ("COCOS (KEELING) ISLANDS", "CC"),
    ("COLOMBIA", "CO"), ("COMMONWEALTH OF DOMINICA", "DM"),
    ("COMMONWEALTH OF THE BAHAMAS", "BS"), ("COMMONWEALTH OF THE NORTHERN MARIANA ISLANDS", "MP"),
    ("COMOROS", "KM"), ("CONGO", "CG"),
    ("CONGO, THE DEMOCRATIC REPUBLIC OF THE", "CD"), ("COOK ISLANDS", "CK"),
    ("COSTA RICA", "CR"), ("CROATIA", "HR"),
    ("CUBA", "CU"), ("CURAÇAO", "CW"),
    ("CYPRUS", "CY"), ("CZECH REPUBLIC", "CZ"),
    ("CZECHIA", "CZ"), ("CÔTE D'IVOIRE", "CI"),
    ("DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA", "KP"), ("DEMOCRATIC REPUBLIC OF SAO TOME AND PRINCIPE", "ST"),
    ("DEMOCRATIC REPUBLIC OF TIMOR-LESTE", "TL"), ("DEMOCRATIC SOCIALIST REPUBLIC OF SRI LANKA", "LK"),
    ("DENMARK", "DK"), ("DJIBOUTI", "DJ"),
    ("DOMINICA", "DM"), ("DOMINICAN REPUBLIC", "DO"),
    ("EASTERN REPUBLIC OF URUGUAY", "UY"), ("ECUADOR", "EC"),
    ("EGYPT", "EG"), ("EL SALVADOR", "SV"),
    ("EQUATORIAL GUINEA", "GQ"), ("ERITREA", "ER"),
    ("ESTONIA", "EE"), ("ESWATINI", "SZ"),
    ("ETHIOPIA", "ET"), ("FALKLAND ISLANDS (MALVINAS)", "FK"),
    ("FAROE ISLANDS", "FO"), ("FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA", "ET"),
    ("FEDERAL DEMOCRATIC REPUBLIC OF NEPAL", "NP"), ("FEDERAL REPUBLIC OF GERMANY", "DE"),
    ("FEDERAL REPUBLIC OF NIGERIA", "NG"), ("FEDERAL REPUBLIC OF SOMALIA", "SO"),
    ("FEDERATED STATES OF MICRONESIA", "FM"), ("FEDERATIVE REPUBLIC OF BRAZIL", "BR"),
    ("FIJI", "FJ"), ("FINLAND", "FI"),
    ("FRANCE", "FR"), ("FRENCH GUIANA", "GF"),
    ("FRENCH POLYNESIA", "PF"), ("FRENCH REPUBLIC", "FR"),
    ("FRENCH SOUTHERN TERRITORIES", "TF"), ("GABON", "GA"),
    ("GABONESE REPUBLIC", "GA"), ("GAMBIA", "GM"),
    ("GEORGIA", "GE"), ("GERMANY", "DE"),
    ("GHANA", "GH"), ("GIBRALTAR", "GI"),
    ("GRAND DUCHY OF LUXEMBOURG", "LU"), ("GREECE", "GR"),
    ("GREENLAND", "GL"), ("GRENADA", "GD"),
    ("GUADELOUPE", "GP"), ("GUAM", "GU"),
    ("GUATEMALA", "GT"), ("GUERNSEY", "GG"),
    ("GUINEA", "GN"), ("GUINEA-BISSAU", "GW"),
    ("GUYANA", "GY"), ("HAITI", "HT"),
    ("HASHEMITE KINGDOM OF JORDAN", "JO"), ("HEARD ISLAND AND MCDONALD ISLANDS", "HM"),
    ("HELLENIC REPUBLIC", "GR"), ("HOLY SEE (VATICAN CITY STATE)", "VA"),
    ("HONDURAS", "HN"), ("HONG KONG", "HK"),
    ("HONG KONG SPECIAL ADMINISTRATIVE REGION OF CHINA", "HK"), ("HUNGARY", "HU"),
    ("ICELAND", "IS"), ("INDEPENDENT STATE OF PAPUA NEW GUINEA", "PG"),
    ("INDEPENDENT STATE OF SAMOA", "WS"), ("INDIA", "IN"),
    ("INDONESIA", "ID"), ("IRAN", "IR"),
    ("IRAN, ISLAMIC REPUBLIC OF", "IR"), ("IRAQ", "IQ"),
    ("IRELAND", "IE"), ("ISLAMIC REPUBLIC OF AFGHANISTAN", "AF"),
    ("ISLAMIC REPUBLIC OF IRAN", "IR"), ("ISLAMIC REPUBLIC OF MAURITANIA", "MR"),
    ("ISLAMIC REPUBLIC OF PAKISTAN", "PK"), ("ISLE OF MAN", "IM"),
    ("ISRAEL", "IL"), ("ITALIAN REPUBLIC", "IT"),
    ("ITALY", "IT"), ("JAMAICA", "JM"),
    ("JAPAN", "JP"), ("JERSEY", "JE"),
    ("JORDAN", "JO"), ("KAZAKHSTAN", "KZ"),
    ("KENYA", "KE"), ("KINGDOM OF BAHRAIN", "BH"),
    ("KINGDOM OF BELGIUM", "BE"), ("KINGDOM OF BHUTAN", "BT"),
    ("KINGDOM OF CAMBODIA", "KH"), ("KINGDOM OF DENMARK", "DK"),
    ("KINGDOM OF ESWATINI", "SZ"), ("KINGDOM OF LESOTHO", "LS"),
    ("KINGDOM OF MOROCCO", "MA"), ("KINGDOM OF NORWAY", "NO"),
    ("KINGDOM OF SAUDI ARABIA", "SA"), ("KINGDOM OF SPAIN", "ES"),
    ("KINGDOM OF SWEDEN", "SE"), ("KINGDOM OF THAILAND", "TH"),
    ("KINGDOM OF THE NETHERLANDS", "NL"), ("KINGDOM OF TONGA", "TO"),
    ("KIRIBATI", "KI"), ("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "KP"),
    ("KOREA, REPUBLIC OF", "KR"), ("KUWAIT", "KW"),
    ("KYRGYZ REPUBLIC", "KG"), ("KYRGYZSTAN", "KG"),
    ("LAO PEOPLE'S DEMOCRATIC REPUBLIC", "LA"), ("LAOS", "LA"),
    ("LATVIA", "LV"), ("LEBANESE REPUBLIC", "LB"),
    ("LEBANON", "LB"), ("LESOTHO", "LS"),
    ("LIBERIA", "LR"), ("LIBYA", "LY"),
    ("LIECHTENSTEIN", "LI"), ("LITHUANIA", "LT"),
    ("LUXEMBOURG", "LU"), ("MACAO", "MO"),
    ("MACAO SPECIAL ADMINISTRATIVE REGION OF CHINA", "MO"), ("MADAGASCAR", "MG"),
    ("MALAWI", "MW"), ("MALAYSIA", "MY"),
    ("MALDIVES", "MV"), ("MALI", "ML"),
    ("MALTA", "MT"), ("MARSHALL ISLANDS", "MH"),
    ("MARTINIQUE", "MQ"), ("MAURITANIA", "MR"),
    ("MAURITIUS", "MU"), ("MAYOTTE", "YT"),
    ("MEXICO", "MX"), ("MICRONESIA, FEDERATED STATES OF", "FM"),
    ("MOLDOVA", "MD"), ("MOLDOVA, REPUBLIC OF", "MD"),
    ("MONACO", "MC"), ("MONGOLIA", "MN"),
    ("MONTENEGRO", "ME"), ("MONTSERRAT", "MS"),
    ("MOROCCO", "MA"), ("MOZAMBIQUE", "MZ"),
    ("MYANMAR", "MM"), ("NAMIBIA", "NA"),
    ("NAURU", "NR"), ("NEPAL", "NP"),
    ("NETHERLANDS", "NL"), ("NEW CALEDONIA", "NC"),
    ("NEW ZEALAND", "NZ"), ("NICARAGUA", "NI"),
    ("NIGER", "NE"), ("NIGERIA", "NG"),
    ("NIUE", "NU"), ("NORFOLK ISLAND", "NF"),
    ("NORTH KOREA", "KP"), ("NORTH MACEDONIA", "MK"),
    ("NORTHERN MARIANA ISLANDS", "MP"), ("NORWAY", "NO"),
    ("OMAN", "OM"), ("PAKISTAN", "PK"),
    ("PALAU", "PW"), ("PALESTINE, STATE OF", "PS"),
    ("PANAMA", "PA"), ("PAPUA NEW GUINEA", "PG"),
    ("PARAGUAY", "PY"), ("PEOPLE'S DEMOCRATIC REPUBLIC OF ALGERIA", "DZ"),
    ("PEOPLE'S REPUBLIC OF BANGLADESH", "BD"), ("PEOPLE'S REPUBLIC OF CHINA", "CN"),
    ("PERU", "PE"), ("PHILIPPINES", "PH"),
    ("PITCAIRN", "PN"), ("PLURINATIONAL STATE OF BOLIVIA", "BO"),
    ("POLAND", "PL"), ("PORTUGAL", "PT"),
    ("PORTUGUESE REPUBLIC", "PT"), ("PRINCIPALITY OF ANDORRA", "AD"),
    ("PRINCIPALITY OF LIECHTENSTEIN", "LI"), ("PRINCIPALITY OF MONACO", "MC"),
    ("PUERTO RICO", "PR"), ("QATAR", "QA"),
    ("REPUBLIC OF ALBANIA", "AL"), ("REPUBLIC OF ANGOLA", "AO"),
    ("REPUBLIC OF ARMENIA", "AM"), ("REPUBLIC OF AUSTRIA", "AT"),
    ("REPUBLIC OF AZERBAIJAN", "AZ"), ("REPUBLIC OF BELARUS", "BY"),
    ("REPUBLIC OF BENIN", "BJ"), ("REPUBLIC OF BOSNIA AND HERZEGOVINA", "BA"),
    ("REPUBLIC OF BOTSWANA", "BW"), ("REPUBLIC OF BULGARIA", "BG"),
    ("REPUBLIC OF BURUNDI", "BI"), ("REPUBLIC OF CABO VERDE", "CV"),
    ("REPUBLIC OF CAMEROON", "CM"), ("REPUBLIC OF CHAD", "TD"),
    ("REPUBLIC OF CHILE", "CL"), ("REPUBLIC OF COLOMBIA", "CO"),
    ("REPUBLIC OF COSTA RICA", "CR"), ("REPUBLIC OF CROATIA", "HR"),
    ("REPUBLIC OF CUBA", "CU"), ("REPUBLIC OF CYPRUS", "CY"),
    ("REPUBLIC OF CÔTE D'IVOIRE", "CI"), ("REPUBLIC OF DJIBOUTI", "DJ"),
    ("REPUBLIC OF ECUADOR", "EC"), ("REPUBLIC OF EL SALVADOR", "SV"),
    ("REPUBLIC OF EQUATORIAL GUINEA", "GQ"), ("REPUBLIC OF ESTONIA", "EE"),
    ("REPUBLIC OF FIJI", "FJ"), ("REPUBLIC OF FINLAND", "FI"),
    ("REPUBLIC OF GHANA", "GH"), ("REPUBLIC OF GUATEMALA", "GT"),
    ("REPUBLIC OF GUINEA", "GN"), ("REPUBLIC OF GUINEA-BISSAU", "GW"),
    ("REPUBLIC OF GUYANA", "GY"), ("REPUBLIC OF HAITI", "HT"),
    ("REPUBLIC OF HONDURAS", "HN"), ("REPUBLIC OF ICELAND", "IS"),
    ("REPUBLIC OF INDIA", "IN"), ("REPUBLIC OF INDONESIA", "ID"),
    ("REPUBLIC OF IRAQ", "IQ"), ("REPUBLIC OF KAZAKHSTAN", "KZ"),
    ("REPUBLIC OF KENYA", "KE"), ("REPUBLIC OF KIRIBATI", "KI"),
    ("REPUBLIC OF LATVIA", "LV"), ("REPUBLIC OF LIBERIA", "LR"),
    ("REPUBLIC OF LITHUANIA", "LT"), ("REPUBLIC OF MADAGASCAR", "MG"),
    ("REPUBLIC OF MALAWI", "MW"), ("REPUBLIC OF MALDIVES", "MV"),
    ("REPUBLIC OF MALI", "ML"), ("REPUBLIC OF MALTA", "MT"),
    ("REPUBLIC OF MAURITIUS", "MU"), ("REPUBLIC OF MOLDOVA", "MD"),
    ("REPUBLIC OF MOZAMBIQUE", "MZ"), ("REPUBLIC OF MYANMAR", "MM"),
    ("REPUBLIC OF NAMIBIA", "NA"), ("REPUBLIC OF NAURU", "NR"),
    ("REPUBLIC OF NICARAGUA", "NI"), ("REPUBLIC OF NORTH MACEDONIA", "MK"),
    ("REPUBLIC OF PALAU", "PW"), ("REPUBLIC OF PANAMA", "PA"),
    ("REPUBLIC OF PARAGUAY", "PY"), ("REPUBLIC OF PERU", "PE"),
    ("REPUBLIC OF POLAND", "PL"), ("REPUBLIC OF SAN MARINO", "SM"),
    ("REPUBLIC OF SENEGAL", "SN"), ("REPUBLIC OF SERBIA", "RS"),
    ("REPUBLIC OF SEYCHELLES", "SC"), ("REPUBLIC OF SIERRA LEONE", "SL"),
    ("REPUBLIC OF SINGAPORE", "SG"), ("REPUBLIC OF SLOVENIA", "SI"),
    ("REPUBLIC OF SOUTH AFRICA", "ZA"), ("REPUBLIC OF SOUTH SUDAN", "SS"),
    ("REPUBLIC OF SURINAME", "SR"), ("REPUBLIC OF TAJIKISTAN", "TJ"),
    ("REPUBLIC OF THE CONGO", "CG"), ("REPUBLIC OF THE GAMBIA", "GM"),
    ("REPUBLIC OF THE MARSHALL ISLANDS", "MH"), ("REPUBLIC OF THE NIGER", "NE"),
    ("REPUBLIC OF THE PHILIPPINES", "PH"), ("REPUBLIC OF THE SUDAN", "SD"),
    ("REPUBLIC OF TRINIDAD AND TOBAGO", "TT"), ("REPUBLIC OF TUNISIA", "TN"),
    ("REPUBLIC OF TÜRKIYE", "TR"), ("REPUBLIC OF UGANDA", "UG"),
    ("REPUBLIC OF UZBEKISTAN", "UZ"), ("REPUBLIC OF VANUATU", "VU"),
    ("REPUBLIC OF YEMEN", "YE"), ("REPUBLIC OF ZAMBIA", "ZM"),
    ("REPUBLIC OF ZIMBABWE", "ZW"), ("ROMANIA", "RO"),
    ("RUSSIAN FEDERATION", "RU"), ("RWANDA", "RW"),
    ("RWANDESE REPUBLIC", "RW"), ("RÉUNION", "RE"),
    ("SAINT BARTHÉLEMY", "BL"), ("SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", "SH"),
    ("SAINT KITTS AND NEVIS", "KN"), ("SAINT LUCIA", "LC"),
    ("SAINT MARTIN (FRENCH PART)", "MF"), ("SAINT PIERRE AND MIQUELON", "PM"),
    ("SAINT VINCENT AND THE GRENADINES", "VC"), ("SAMOA", "WS"),
    ("SAN MARINO", "SM"), ("SAO TOME AND PRINCIPE", "ST"),
    ("SAUDI ARABIA", "SA"), ("SENEGAL", "SN"),
    ("SERBIA", "RS"), ("SEYCHELLES", "SC"),
    ("SIERRA LEONE", "SL"), ("SINGAPORE", "SG"),
    ("SINT MAARTEN (DUTCH PART)", "SX"), ("SLOVAK REPUBLIC", "SK"),
    ("SLOVAKIA", "SK"), ("SLOVENIA", "SI"),
    ("SOCIALIST REPUBLIC OF VIET NAM", "VN"), ("SOLOMON ISLANDS", "SB"),
    ("SOMALIA", "SO"), ("SOUTH AFRICA", "ZA"),
    ("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "GS"), ("SOUTH KOREA", "KR"),
    ("SOUTH SUDAN", "SS"), ("SPAIN", "ES"),
    ("SRI LANKA", "LK"), ("STATE OF ISRAEL", "IL"),
    ("STATE OF KUWAIT", "KW"), ("STATE OF QATAR", "QA"),
    ("SUDAN", "SD"), ("SULTANATE OF OMAN", "OM"),
    ("SURINAME", "SR"), ("SVALBARD AND JAN MAYEN", "SJ"),
    ("SWEDEN", "SE"), ("SWISS CONFEDERATION", "CH"),
    ("SWITZERLAND", "CH"), ("SYRIA", "SY"),
    ("SYRIAN ARAB REPUBLIC", "SY"), ("TAIWAN", "TW"),
    ("TAIWAN, PROVINCE OF CHINA", "TW"), ("TAJIKISTAN", "TJ"),
    ("TANZANIA", "TZ"), ("TANZANIA, UNITED REPUBLIC OF", "TZ"),
    ("THAILAND", "TH"), ("THE STATE OF ERITREA", "ER"),
    ("THE STATE OF PALESTINE", "PS"), ("TIMOR-LESTE", "TL"),
    ("TOGO", "TG"), ("TOGOLESE REPUBLIC", "TG"),
    ("TOKELAU", "TK"), ("TONGA", "TO"),
    ("TRINIDAD AND TOBAGO", "TT"), ("TUNISIA", "TN"),
    ("TURKMENISTAN", "TM"), ("TURKS AND CAICOS ISLANDS", "TC"),
    ("TUVALU", "TV"), ("TÜRKIYE", "TR"),
    ("UGANDA", "UG"), ("UKRAINE", "UA"),
    ("UNION OF THE COMOROS", "KM"), ("UNITED ARAB EMIRATES", "AE"),
    ("UNITED KINGDOM", "GB"), ("UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND", "GB"),
    ("UNITED MEXICAN STATES", "MX"), ("UNITED REPUBLIC OF TANZANIA", "TZ"),
    ("UNITED STATES", "US"), ("UNITED STATES MINOR OUTLYING ISLANDS", "UM"),
    ("UNITED STATES OF AMERICA", "US"), ("URUGUAY", "UY"),
    ("UZBEKISTAN", "UZ"), ("VANUATU", "VU"),
    ("VENEZUELA", "VE"), ("VENEZUELA, BOLIVARIAN REPUBLIC OF", "VE"),
    ("VIET NAM", "VN"), ("VIETNAM", "VN"),
    ("VIRGIN ISLANDS OF THE UNITED STATES", "VI"), ("VIRGIN ISLANDS, BRITISH", "VG"),
    ("VIRGIN ISLANDS, U.S.", "VI"), ("WALLIS AND FUTUNA", "WF"),
    ("WESTERN SAHARA", "EH"), ("YEMEN", "YE"),
    ("ZAMBIA", "ZM"), ("ZIMBABWE", "ZW"),
    ("ÅLAND ISLANDS", "AX"),
];

/// Every ISO 3166-1 alpha-2 code, plus the user-assigned `XK` (Kosovo) the
/// corpus and the fold both use. Generated with the tables above.
///
/// This exists so a report can say which stored country values are not codes
/// at all. The length test that reads like the same question is not: `VU` is
/// two characters and a real code, and it is still wrong for the Bulgarian
/// bodies filed under it (issue 319's per-case half) — while `ZZ` is two
/// characters and no country whatsoever, which only a list can tell you.
pub const ALPHA2: &[&str] = &[
    "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR", "AS", "AT",
    "AU", "AW", "AX", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI",
    "BJ", "BL", "BM", "BN", "BO", "BQ", "BR", "BS", "BT", "BV", "BW", "BY",
    "BZ", "CA", "CC", "CD", "CF", "CG", "CH", "CI", "CK", "CL", "CM", "CN",
    "CO", "CR", "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM",
    "DO", "DZ", "EC", "EE", "EG", "EH", "ER", "ES", "ET", "FI", "FJ", "FK",
    "FM", "FO", "FR", "GA", "GB", "GD", "GE", "GF", "GG", "GH", "GI", "GL",
    "GM", "GN", "GP", "GQ", "GR", "GS", "GT", "GU", "GW", "GY", "HK", "HM",
    "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IM", "IN", "IO", "IQ", "IR",
    "IS", "IT", "JE", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN",
    "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS",
    "LT", "LU", "LV", "LY", "MA", "MC", "MD", "ME", "MF", "MG", "MH", "MK",
    "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW",
    "MX", "MY", "MZ", "NA", "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP",
    "NR", "NU", "NZ", "OM", "PA", "PE", "PF", "PG", "PH", "PK", "PL", "PM",
    "PN", "PR", "PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS", "RU", "RW",
    "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SJ", "SK", "SL", "SM",
    "SN", "SO", "SR", "SS", "ST", "SV", "SX", "SY", "SZ", "TC", "TD", "TF",
    "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO", "TR", "TT", "TV", "TW",
    "TZ", "UA", "UG", "UM", "US", "UY", "UZ", "VA", "VC", "VE", "VG", "VI",
    "VN", "VU", "WF", "WS", "YE", "YT", "ZA", "ZM", "ZW",
];

/// Is this a real alpha-2 country code (or Kosovo's user-assigned `XK`)?
pub fn is_alpha2(code: &str) -> bool {
    let up = code.trim().to_ascii_uppercase();
    up == "XK" || ALPHA2.binary_search(&up.as_str()).is_ok()
}
